[package]
name = "rust-cpp-ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffi-sys = { path = "../ffi-sys" }

[build-dependencies]
cc = "1.0"
